### ISSUE TITLE
v1.0 Release Checklist

### ISSUE THREAD

**Issue by Sonictherocketman** [adventurerscodex/hypnos#3]
This is a working issue for a checklist to open source Hypnos.

- [ ] Improve Documentation
- [ ] Add tests (at least to 80%)
- [ ] Add CI and Coverage monitoring (via travis and Coveralls)
- [ ] Make NPM installable
- [ ] Add Install instructions and improve README
